foodgram/urls.py
from django.conf.urls import handler404, url  # noqa
from django.contrib import admin
from django.contrib.flatpages.views import flatpage
from django.urls import path, include
from django.views.generic import RedirectView

from foodgram import settings

handler404 = "apps.recipes.views.page_not_found"  # noqa

urlpatterns = [
    url(r'^favicon\.ico$', RedirectView.as_view(
        url='/staticfiles/images/favicon.ico', permanent=True)),
    path('admin/panel/', admin.site.urls, name='admin-panel'),
    path('auth/', include('apps.users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('api/', include('apps.api.urls')),
    path('about-author/', flatpage, {'url': '/about-author/'}, name='author'),
    path('about-spec/', flatpage, {'url': '/about-spec/'}, name='spec'),
    path('', include('apps.recipes.urls')),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)

apps/recipes/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.db.models import UniqueConstraint

User = get_user_model()


class Ingredient(models.Model):
    title = models.CharField(max_length=255, db_index=True, unique=True)
    dimension = models.CharField(max_length=20, db_index=True)

    def __str__(self):
        return f'Ingredient name: {self.title}, dimension {self.dimension}'


class Tag(models.Model):
    name = models.CharField(max_length=50, null=True)
    slug = models.SlugField(max_length=50, null=True, unique=True)
    color = models.CharField(verbose_name='check box style', max_length=50,
                             null=True)

    def __str__(self):
        return f'Tag: {self.name}'


class Recipe(models.Model):
    name = models.CharField(
        verbose_name='recipe name',
        max_length=255,
        db_index=True
    )
    author = models.ForeignKey(
        User,
        verbose_name='authors recipe',
        on_delete=models.CASCADE,
        related_name='recipes',
        db_index=True
    )
    description = models.TextField(verbose_name='recipe description')
    cooking_time = models.IntegerField()
    image = models.ImageField(upload_to='recipe')
    created = models.DateTimeField(verbose_name='time publication',
                                   auto_now=True)
    ingredients = models.ManyToManyField(
        Ingredient,
        through='RecipeIngredient'
    )
    tag = models.ManyToManyField(
        Tag,
        related_name='recipe_tag',
    )

    class Meta:
        ordering = ['-created']

    def __str__(self):
        return f'Recipe name: {self.name}, author: {self.author}'

    def is_favorite(self, user_id):
        response = FavoritesRecipes.objects.filter(
            user=user_id, favorites=self.id
        ).exists()
        return response

    def is_in_cart(self, user_id):
        response = ShoppingList.objects.filter(
            user=user_id, recipe=self.id
        ).exists()
        return response


class RecipeIngredient(models.Model):
    recipe = models.ForeignKey(
        Recipe,
        related_name='recipe_ingredients',
        on_delete=models.CASCADE)
    ingredient = models.ForeignKey(
        Ingredient,
        on_delete=models.CASCADE
    )
    amount = models.IntegerField()


class SubscriptionsUsers(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='follower'
    )
    author = models.ForeignKey(
        User, on_delete=models.CASCADE,
        related_name='following'
    )

    class Meta:
        UniqueConstraint(fields=['user', 'author'],
                         name='unique_Subscriptions')

    def __str__(self):
        return f'User: {self.user}, author: {self.author}'

    def is_following(self, author_id):
        response = SubscriptionsUsers.objects.select_related(
            'user', 'author'
        ).filter(
            user=self.id, author=author_id
        ).exists()
        return response


class FavoritesRecipes(models.Model):
    favorites = models.ForeignKey(
        Recipe,
        on_delete=models.CASCADE,
    )
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
    )

    class Meta:
        UniqueConstraint(fields=['user', 'favorites'],
                         name='unique_favorites_recipes')

    def __str__(self):
        return f'User: {self.user}, favorite recipe: {self.favorites.name}'


class ShoppingList(models.Model):
    recipe = models.ForeignKey(
        Recipe,
        related_name='shopping_list',
        on_delete=models.CASCADE,
    )
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
    )

    class Meta:
        UniqueConstraint(fields=['user', 'recipe'],
                         name='unique_shopping_list')

    def __str__(self):
        return f'User: {self.user}, recipe_id: {self.recipe.id}'

templates/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}Заголовок страницы{% endblock title %} | FoodGram</title>

    <!-- Загрузка css -->
    {% block static_css %}{% endblock %}

</head>
<body class="body">

<!-- Загрузка Nav бар -->
{% block nav %}{% endblock %}

<!-- Содержимое страницы -->
<main class="main container">
    {% block content %}{% endblock content %}
</main>


<!-- Загрузка footer -->
{% include 'footer.html' %}

<!-- Загрузка javascript -->
{% block static_js %}{% endblock %}

</body>
</html>

templates/container-edit-recipe.html
<div class="form-container">
    <form class="form" method="post" enctype="multipart/form-data">
        {% csrf_token %}

        <div class="form__group">
            <label for="id_name" class="form__label">Название рецепта</label>
            <div class="form__field-group">
                <input type="text" id="id_name" name="name" class="form__input"
                       value="{{ form.name.value | default_if_none:'' }}">
                <span class="form__error">{{ form.name.errors }}</span>
            </div>
        </div>
        <div class="form__group">
            <p class="form__label">Теги</p>
            <div class="form__field-group">
                <div class="tags">

                    {% for tag_choice, tag_value in form.tags.field.choices %}
                        <div class="tags___item">
                            <input
                                    type="checkbox"
                                    name="tags"
                                    value="{{ tag_choice.instance.slug }}" id="id_{{ tag_choice.instance.slug }}"
                                    class="tags__checkbox tags__checkbox_style_{{ tag_choice.instance.color }}"
                                    {% if tag_choice.instance in form.instance.tag.all %}checked{% endif %}>
                            <label for="id_{{ tag_choice.instance.value }}" class="tags__label">
                                {{ tag_choice.instance.name }}
                            </label>
                        </div>
                    {% endfor %}

                </div>
                <span class="form__error">{{ form.tags.errors }}</span>
            </div>
        </div>
        <div class="form__group">
            <label for="nameIngredient" class="form__label">Ингредиенты</label>
            <div class="form__field-group">
                <div class="form__field-group-ingredientes">
                    <div class="form__dropdown">
                        <input type="text" id="nameIngredient" class="form__input">
                        <div class="form__dropdown-items"></div>
                    </div>
                    <input type="number" id="cantidad" name="cooking_time" class="form__input">
                    <label for=" cantidad" class="form__label" id="cantidadVal">шт.</label>
                </div>
                <div class="form__field-group-ingredientes-container">
                    {% if form.ingredients %}
                        {% for ing in recipe.recipe_ingredients.all %}

                            <div id="ing_{{ forloop.counter }}" class="form__field-item-ingredient">
                                <span>{{ ing.ingredient.title }} {{ ing.amount }} {{ ing.ingredient.dimension }}</span><span
                                    class="form__field-item-delete"></span>

                                <input id="nameIngredient_{{ forloop.counter }}"
                                       name="nameIngredient_{{ forloop.counter }}" type="hidden"
                                       value="{{ ing.ingredient.title }}">

                                <input id="valueIngredient_{{ forloop.counter }}"
                                       name="valueIngredient_{{ forloop.counter }}" type="hidden"
                                       value="{{ ing.amount }}">

                                <input id="unitsIngredient_{{ forloop.counter }}"
                                       name="unitsIngredient_{{ forloop.counter }}" type="hidden"
                                       value="{{ ing.ingredient.dimension }}">
                            </div>

                        {% endfor %}
                    {% endif %}

                </div>
                <span class="form__ingredient-link" id="addIng">Добавить ингредиент</span>
                <span class="form__error">{{ form.ingredients.errors }}</span>
            </div>
        </div>
        <div class="form__group">
            <label for="id_time" class="form__label">Время приготовления</label>
            <div class="form__field-group form__field-group_time">
                <input type="text" id="id_time" name="cooking_time" class="form__input"
                       value="{{ form.cooking_time.value |default_if_none:0 }}">
                <label for="id_time" class="form__label">минут</label>
                <span class="form__error">{{ form.cooking_time.errors }}</span>
            </div>
        </div>
        <div class="form__group">
            <label for="id_description" class="form__label">Описание</label>
            <div class="form__field-group">
                <textarea name="description" id="id_description" rows="8"
                          class="form__textarea">{{ form.description.value|default_if_none:'' }}</textarea>
                <span class="form__error">{{ form.description.errors }}</span>
            </div>
        </div>
        <div class="form__group">
            <span class="form__label">Загрузить фото</span>
            <div class="form__field-group">
                {{ form.image.widget }}
                <input type="file" name="image" id="id_file" value="{{ form.image.value }}">
                <span class="form__input-info">При редактировании фотография сохраняется</span>
                <span class="form__error">{{ form.image.errors }}</span>
            </div>
        </div>
        <div class="form__footer">
            <button class="button button_style_blue">Создать рецепт</button>
        </div>
    </form>
</div>

templates/container-favorites-recipes-items.html
{% load static %}

<div class="card-list">
    {% for favorites_recipe in page %}
        <div class="card" data-id="{{ favorites_recipe.favorites.id }}">
            <a href="{% url 'recipe_detail' favorites_recipe.favorites.id %}" class="link"><img
                    src="{% get_media_prefix %}{{ favorites_recipe.favorites.image }}"
                    alt="Изображение блюда"
                    class="card__image"></a>
            <div class="card__body">
                <a class="card__title link"
                   href="{% url 'recipe_detail' favorites_recipe.favorites.id %}">{{ favorites_recipe.favorites.name }}</a>
                <ul class="card__items">

                    <!--Загрузка тегов  в рецепте-->
                    {% include 'container-tags.html' with recipe=favorites_recipe.favorites %}

                </ul>
                <div class="card__items card__items_column">
                    <p class="card__text"><span class="icon-time"></span> {{ favorites_recipe.favorites.cooking_time }} минут
                    </p>
                    <p class="card__text"><span class="icon-user"></span>
                        <a href="{% url 'authors-recipes' favorites_recipe.favorites.author %}"
                           style="color: black">{{ favorites_recipe.favorites.author }}
                        </a>
                    </p>
                </div>
            </div>
            {% if user.is_authenticated %}
            <div class="card__footer">

                <!-- Кнопка "Добавить в покупки"-->
                {% include 'shopping-list-button.html' with recipe=favorites_recipe.favorites %}

                <!--Кнопка "избранное"-->
                {% include 'favorites-button.html' with recipe=favorites_recipe.favorites %}

            </div>
            {% endif %}
        </div>
    {% endfor %}
</div>

templates/container-header-tags.html
{% load recipe_filter %}

<ul class="tags">
    {% with filter_value=request.GET|get_filter_values %}
        {% for tag in all_tags %}
            <li class="tags__item">
                <a id="{{ tag.slug }}"
                   class="tags__checkbox tags__checkbox_style_{{ tag.color }}
                   {% if tag.slug in filter_value %} tags__checkbox_active {% endif %}"
                   href="?{{request|get_filter_link:tag}}"></a>
                <span class="tags__label">{{ tag.name }}</span>
            </li>
        {% endfor %}
    {% endwith %}
</ul>

templates/container-my-following.html
{% load static %}
<div class="card-list">
    {% for authors in page %}
        <div class="card-user" data-author="{{ authors.author_id }}">
            <div class="card-user__header">
                <h2 class="card-user__title"><a href="{% url 'authors-recipes' authors.author %}"
                                                style="color: black">{{ authors.author }}</a></h2>
            </div>
            {% for recipe in authors.author.recipes.all|slice:":3" %}
                <div class="card-user__body">
                    <ul class="card-user__items">
                        <li class="card-user__item">
                            <div class="recipe">
                                <a href="{% url 'recipe_detail' recipe.id %}" class="link">
                                    <img src="{% get_media_prefix %}{{ recipe.image }}" alt="Изображение блюда"
                                         class="recipe__image"></a>
                                <h3 class="recipe__title">
                                    {{ recipe.name }}</h3>
                                <p class="recipe__text"><span class="icon-time"></span> {{ recipe.cooking_time }} минут
                                </p>
                            </div>
                        </li>
                    </ul>
                </div>
            {% endfor %}
            <li class="card-user__item">
                {# Кол-во у автора рецептов и минус 3, которые уже есть на странице #}
                {% if authors.author.recipes.all.count|add:-3 > 0 %}
                    <a href="{% url 'authors-recipes' authors.author.username %}" class="card-user__link link">Еще
                        {{ authors.author.recipes.all.count|add:-3 }} рецептов...</a>
                {% endif %}
            </li>

            <div class="card-user__footer">
                <button class="button button_style_light-blue button_size_auto" name="subscribe">Отписаться
                </button>
            </div>
        </div>
    {% endfor %}
</div>

templates/container-tags.html
{% for tag in recipe.tag.all %}
    {% if tag.slug == 'breakfast' %}
        <li class="card__item"><span class="badge badge_style_orange">Завтрак</span></li>
    {% elif tag.slug == 'lunch' %}
        <li class="card__item"><span class="badge badge_style_green">Обед</span></li>
    {% elif tag.slug == 'dinner' %}
        <li class="card__item"><span class="badge badge_style_purple">Ужин</span></li>
    {% endif %}
{% endfor %}

templates/following-button-single-card.html
{% load recipe_filter %}

{% if user.is_authenticated %}
    {% if user|is_following:recipe.author.id %}
        <button class="button button_style_light-blue button_size_auto button_style_light-blue-outline"
                name="subscribe"><span class="icon-check button__icon"></span> Отписаться от автора
        </button>
    {% else %}
        {% if not recipe.author == request.user %}
            <button class="button button_style_light-blue button_size_auto" name="subscribe" data-out>
                Подписаться на автора
            </button>
        {% endif %}
    {% endif %}
{% endif %}

templates/following-button.html
{% load recipe_filter %}

{% if user.is_authenticated %}

    <div class="author-subscribe" data-author="{{ author.id }}">
        {% if user|is_following:author.id %}
            <p style="padding: 0 0 2em 0;">
                <button class="button button_style_light-blue button_size_auto button_style_light-blue-outline"
                        name="subscribe"><span class="icon-check button__icon"></span> Отписаться от автора
                </button>
                {% else %}
                {% for recipe in page %}
                    {% if not recipe.author == request.user %}
                        {% ifchanged %}
                            <p style="padding: 0 0 2em 0;">
                                <button class="button button_style_light-blue button_size_auto" name="subscribe"
                                        data-out>
                                    Подписаться на автора
                                </button>
                            </p>
                        {% endifchanged %}
                    {% endif %}
                {% endfor %}
        {% endif %}
    </div>
{% endif %}

templates/footer.html
<footer class="footer">
    <div class="footer__container container">
        <a href="{% url 'index' %}" class="footer__brand link">Продуктовый помощник</a>
        <ul class="footer__items">
            <li class="footer__item"><a href="{% url 'author' %}" class="footer__link link">Об авторе </a></li>
            <li class="footer__item"><a href="{% url 'spec' %}" class="footer__link link">Технологии</a></li>
        </ul>
    </div>
</footer>

templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Рецепты{% endblock title %}

{% block static_css %}
    <link rel="stylesheet" href="{% static 'pages/index.css' %}">
{% endblock %}

{% block nav %}
    {% include 'nav.html' with index=True disabled_button=True %}
{% endblock %}

{% block content %}
    <!-- Header контейнера c тегами -->
    <div class="main__header">
        <h1 class="main__title">Рецепты</h1>
        {% include 'container-header-tags.html' %}
    </div>

    <!-- Карточки с рецептами -->
    {% include 'container-recipes-items.html' %}

    <!-- Паджинатор -->
    {% if page.has_other_pages %}
        <ul class="pagination justify-content-center">
            {% include "paginator.html" with items=page paginator=paginator %}
        </ul>
    {% endif %}

{% endblock content %}



{% block static_js %}
    {% csrf_token %}

    <script src="{% static 'js/config/config.js' %}"></script>

    <script src="{% static 'js/components/MainCards.js' %}"></script>
    <script src="{% static 'js/components/Purchpurachases.js' %}"></script>

    <script src="{% static 'js/components/CardList.js' %}"></script>
    <script src="{% static 'js/components/Header.js' %}"></script>
    <script src="{% static 'js/api/Api.js' %}"></script>

    {% if user.is_anonymous %}
        <script src="{% static 'js/template/indexNotAuth.js' %}"></script>
    {% else %}
        <script src="{% static 'js/components/Favorites.js' %}"></script>
        <script src="{% static 'js/template/indexAuth.js' %}"></script>
    {% endif %}

{% endblock %}

templates/my-following.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Мои подписки{% endblock %}

{% block static_css %}
    <link rel="stylesheet" href="{% static 'pages/myFollow.css' %}">
{% endblock %}

{% block nav %}
    {% include 'nav.html' with my_follower=True %}
{% endblock %}


{% block content %}
    <div class="main__header">
        <h1 class="main__title">Мои подписки</h1>
    </div>

    {% include 'container-my-following.html' %}

    <!-- Паджинатор -->
    {% if page.has_other_pages %}
        <ul class="pagination justify-content-center">
            {% include "paginator.html" with items=page paginator=paginator %}
        </ul>
    {% endif %}
{% endblock %}

{% block static_js %}
    {% csrf_token %}

    <script src="{% static 'js/config/config.js' %}"></script>

    <script src="{% static 'js/components/MainCards.js' %}"></script>
    <script src="{% static 'js/components/MyFollow.js' %}"></script>
    <script src="{% static 'js/components/Subscribe.js' %}"></script>
    <script src="{% static 'js/components/Header.js' %}"></script>

    <script src="{% static 'js/api/Api.js' %}"></script>
    <script src="{% static 'js/template/myFollow.js' %}"></script>

{% endblock %}

templates/nav.html
<header class="header">
    <nav class="nav">
        <div class="nav__container container">

            {% if user.is_authenticated %}

                <li class="nav__item {% if index %}nav__item_active{% endif %}"><a href="{% url 'index' %}"
                                                                                   class="nav__link link">Рецепты</a>
                </li>
                <li class="nav__item {% if my_follower %}nav__item_active{% endif %}"><a
                        href="{% url 'my_followings' %}" class="nav__link link">Мои подписки</a></li>
                <li class="nav__item {% if new_recipe %}nav__item_active{% endif %}"><a href="{% url 'new-recipe' %}"
                                                                                        class="nav__link link">Создать
                    рецепт</a></li>
                <li class="nav__item {% if favorites %}nav__item_active{% endif %}"><a href="{% url 'favorites' %}"
                                                                                       class="nav__link link">Избранное</a>
                </li>
                <li class="nav__item {% if shopping_list %}nav__item_active{% endif %}"><a
                        href="{% url 'shopping-list' %}" class="nav__link link">Список покупок</a>
                    <span
                            class="badge badge_style_blue nav__badge" id="counter">{{ user.shoppinglist_set.count }}</span></li>
                <ul class="nav__items list">
                <li class="nav__item"><a href="{% url 'authors-recipes' user.username %}" class="nav__link link">Я: {{ user.username }}</a></li>
                    <li class="nav__item"><a href="{% url 'password_change' %}" class="nav__link link">Изменить
                        пароль</a></li>
                    <li class="nav__item"><a href="{% url 'logout' %}" class="nav__link link">Выход</a></li>
                </ul>
            {% else %}
                <ul class="nav__items list">
                    <li class="nav__item {% if index %}nav__item_active{% endif %}">
                        <a href="{% url 'index' %}"
                           class="nav__link link">Рецепты</a>
                    </li>
                    <li class="nav__item {% if disabled_button %}nav__item_disabled{% endif %}"><a
                            href="{% url 'shopping-list' %}"
                            class="nav__link link">Список покупок <span
                            class="badge badge_style_blue nav__badge" id="counter">0</span></a></li>
                </ul>
            {% endif %}

            {% if not user.is_authenticated %}

                <ul class="nav__items list">
                <li class="nav__item"><a href="{% url 'login' %}" class="nav__link link">Войти</a></li>
                <li class="nav__item"><a href="{% url 'signup' %}" class="button button_style_blue">Создать
                    аккаунт</a></li>

            {% endif %}
            </ul>
        </div>
    </nav>
</header>

templates/paginator.html
<nav class="pagination" aria-label="Search results pages">
    <ul class="pagination__container">

        {% if items.has_previous %}
            <li class="pagination__item"><a class="pagination__link link"
                                            href="?page={{ items.previous_page_number }}"><span
                    class="icon-left"></span></a>
            </li>

        {% else %}
            <li class="pagination__item"><a class="pagination__link link"><span
                    class="icon-left"></span></a>
            </li>
        {% endif %}

        {% for number in paginator.page_range %}
            {% if items.number == number %}
                <li class="pagination__item pagination__item_active"><a class="pagination__link link"
                                                                        href="?page={{ number }}">{{ number }}</a>
                </li>

            {% else %}
                <li class="pagination__item"><a class="pagination__link link" href="?page={{ number }}">{{ number }}</a>
                </li>
            {% endif %}
        {% endfor %}

        {% if items.has_next %}
            <li class="pagination__item"><a class="pagination__link link"
                                            href="?page={{ items.next_page_number }}"><span
                    class="icon-right"></span></a>
            </li>

        {% else %}
            <li class="pagination__item"><a class="pagination__link link"><span
                    class="icon-right"></span></a>
            </li>
        {% endif %}
    </ul>
</nav>

templates/recipe-edit.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Редактирование рецепта{% endblock %}

{% block static_css %}
    <link rel="stylesheet" href="{% static 'pages/form.css' %}">
{% endblock %}

{% block nav %}
    {% include 'nav.html' %}
{% endblock %}


{% block content %}
    <div class="main__header">
        <h1 class="main__title">Редактирование рецепта</h1>
    </div>

    <!--Загрузка контейнера с редактированием рецепта-->
    {% include 'container-edit-recipe.html' %}
{% endblock %}

{% block static_js %}
    {% csrf_token %}

    <script src="{% static 'js/config/config.js' %}"></script>
    <script src="{% static 'js/api/Api.js' %}"></script>
    <script src="{% static 'js/components/Header.js' %}"></script>
    <script src="{% static 'js/utils/debouncing.js' %}"></script>
    <script src="{% static 'js/template/formRecipe.js' %}"></script>

{% endblock %}